#!/usr/bin/env tsx
// Runner for interactive Telegram auth using teleproto's start() flow.
// Usage: npm run telegram-auth

import 'dotenv/config';
import { createInterface } from 'node:readline';
import { existsSync, appendFileSync } from 'node:fs';
import { TelegramClient } from 'teleproto';
import { StringSession } from 'teleproto/sessions';

const apiId = parseInt(process.env.TELEGRAM_API_ID ?? '', 10);
const apiHash = process.env.TELEGRAM_API_HASH ?? '';

if (!apiId || !apiHash) {
  console.error('Error: TELEGRAM_API_ID and TELEGRAM_API_HASH must be set in .env');
  process.exit(1);
}

const rl = createInterface({ input: process.stdin, output: process.stdout });
function ask(prompt: string): Promise<string> {
  return new Promise((resolve) => rl.question(prompt, resolve));
}

console.log('\n=== CYRUS Telegram Authentication ===\n');
console.log('This will authenticate with Telegram to receive signals from @agentpear.');
console.log('You will need access to your Telegram app to receive the verification code.\n');

const session = new StringSession('');
const client = new TelegramClient(session, apiId, apiHash, {
  connectionRetries: 3,
});

try {
  // teleproto's start() handles the full auth flow via callbacks
  await client.start({
    phoneNumber: async () => {
      const phone = await ask('Enter your phone number (with country code, e.g., +1234567890): ');
      return phone.trim();
    },
    phoneCode: async () => {
      const code = await ask('Enter the verification code you received: ');
      return code.trim();
    },
    password: async () => {
      const pw = await ask('Enter your 2FA password: ');
      return pw.trim();
    },
    onError: (err: Error) => {
      console.error('Auth error:', err.message);
    },
  });

  console.log('\nAuthenticated successfully!');

  // Get session string
  const sessionString = client.session.save() as unknown as string;

  // Verify by fetching from @agentpear
  let verified = false;
  try {
    const entity = await client.getEntity('agentpear');
    const messages = await client.getMessages(entity, { limit: 1 });
    if (messages.length > 0) {
      const preview = messages[0].message.length > 100
        ? messages[0].message.slice(0, 100) + '...'
        : messages[0].message;
      console.log(`\nVerified! Connected to @agentpear channel.`);
      console.log(`Latest message preview: ${preview}`);
      verified = true;
    }
  } catch {
    console.warn('\nWarning: Could not verify @agentpear channel access.');
    console.warn('Make sure you have joined the @agentpear channel on Telegram.');
  }

  // Save to .env
  const saveAnswer = await ask('\nSave session string to .env? (y/n): ');
  if (saveAnswer.trim().toLowerCase() === 'y') {
    const envPath = '.env';
    const line = `\n# Telegram session - generated by cyrus telegram-auth\nTELEGRAM_SESSION_STRING=${sessionString}\n`;
    if (existsSync(envPath)) {
      appendFileSync(envPath, line);
    }
    console.log('Session string saved to .env');
  } else {
    console.log('\nSession string (copy manually):');
    console.log(sessionString);
  }

  if (verified) {
    console.log('\nTelegram setup complete! The agent will receive Pear Protocol signals.');
  }
} catch (err) {
  console.error('\nAuthentication failed:', (err as Error).message);
  process.exit(1);
} finally {
  await client.disconnect();
  rl.close();
}

process.exit(0);
