// Strategy generation types — Self-Evolving Strategy Generator

import type { PerformanceMetrics } from '../../backtest/types.js';

/**
 * Status lifecycle for a generated strategy variant.
 * Flows: generated -> validating -> valid/invalid -> backtesting -> backtest-complete
 *   -> paper-trading -> promoted/eliminated
 */
export type VariantStatus =
  | 'generated'
  | 'validating'
  | 'valid'
  | 'invalid'
  | 'backtesting'
  | 'backtest-complete'
  | 'paper-trading'
  | 'promoted'
  | 'eliminated';

/**
 * A strategy variant generated by the AI code generator.
 */
export interface GeneratedVariant {
  readonly id: string;
  readonly parentStrategy: string;
  readonly sourceCode: string;
  readonly mutationDescription: string;
  readonly generatedAt: number;
  status: VariantStatus;
}

/**
 * Result of validating a generated variant through the full pipeline.
 */
export interface ValidationResult {
  readonly valid: boolean;
  readonly violations: string[];
  readonly syntaxValid: boolean;
  readonly extendsStrategy: boolean;
  readonly riskBoundsValid: boolean;
  readonly safetyCheckPassed: boolean;
}

/**
 * Result of a variant's performance in a tournament round.
 */
export interface TournamentResult {
  readonly variantId: string;
  rank: number;
  readonly sharpeRatio: number;
  readonly maxDrawdown: number;
  readonly totalReturn: number;
  readonly winRate: number;
  readonly profitFactor: number;
  eliminated: boolean;
  eliminationReason: string | null;
  promotedToPaperTrading: boolean;
}

/**
 * Criteria for promoting a paper-traded variant to live trading.
 */
export interface PromotionCriteria {
  readonly minSharpe: number;
  readonly requirePositivePnl: boolean;
  readonly initialAllocationPercent: number;
}

/**
 * A recorded paper trade — signal recorded without real execution.
 */
export interface PaperTradeRecord {
  readonly variantId: string;
  readonly signalTime: number;
  readonly direction: 'long' | 'short';
  readonly entryPrice: number;
  exitPrice: number | null;
  estimatedPnl: number;
  readonly pair: string;
  readonly chainId: number;
}

/**
 * Report explaining a promotion or rejection decision.
 */
export interface PromotionReport {
  readonly variantId: string;
  readonly parentStrategy: string;
  readonly backtestMetrics: TournamentResult;
  readonly paperTradingMetrics: {
    readonly sharpe: number;
    readonly totalPnl: number;
    readonly tradeCount: number;
    readonly winRate: number;
  };
  readonly promotionDecision: 'promoted' | 'rejected';
  readonly reason: string;
  readonly allocatedPercent: number;
}

/**
 * Default promotion criteria.
 */
export const DEFAULT_PROMOTION_CRITERIA: PromotionCriteria = {
  minSharpe: 0.5,
  requirePositivePnl: true,
  initialAllocationPercent: 0.01,
};

/**
 * Configuration for the strategy generation pipeline.
 */
export interface GenerationConfig {
  readonly variantsPerRun: number;
  readonly backtestDays: number;
  readonly paperTradingDays: number;
  readonly tournamentTopN: number;
  readonly maxDrawdownThreshold: number;
  readonly promotionCriteria: PromotionCriteria;
  readonly scheduleIntervalMs: number;
}

/**
 * Default generation configuration.
 */
export const DEFAULT_GENERATION_CONFIG: GenerationConfig = {
  variantsPerRun: 5,
  backtestDays: 30,
  paperTradingDays: 7,
  tournamentTopN: 3,
  maxDrawdownThreshold: 0.20,
  promotionCriteria: DEFAULT_PROMOTION_CRITERIA,
  scheduleIntervalMs: 7 * 24 * 60 * 60 * 1000, // 7 days
};

/**
 * Tracks the history of an evolution cycle.
 */
export interface EvolutionCycleRecord {
  readonly generation: number;
  readonly timestamp: number;
  readonly variantsGenerated: number;
  readonly variantsPromotedToPaperTrading: number;
  readonly variantsPromotedToLive: number;
  readonly variantsEliminated: number;
  readonly currentlyPaperTrading: number;
}

/**
 * Compute paper-trading Sharpe ratio from PaperTradeRecord array.
 * Uses simple returns as daily approximation.
 */
export function computePaperTradingSharpe(records: PaperTradeRecord[]): number {
  const closedTrades = records.filter((r) => r.exitPrice !== null);
  if (closedTrades.length < 2) return 0;

  const returns = closedTrades.map((r) => r.estimatedPnl / Math.max(Math.abs(r.entryPrice), 0.0001));
  const mean = returns.reduce((sum, v) => sum + v, 0) / returns.length;
  const variance = returns.reduce((sum, v) => sum + (v - mean) ** 2, 0) / returns.length;
  const stdDev = Math.sqrt(variance);

  if (stdDev === 0) return 0;

  // Annualized assuming daily trades
  return (mean / stdDev) * Math.sqrt(365);
}

/**
 * Compute paper-trading summary metrics from PaperTradeRecord array.
 */
export function computePaperTradingMetrics(records: PaperTradeRecord[]): {
  sharpe: number;
  totalPnl: number;
  tradeCount: number;
  winRate: number;
} {
  const closedTrades = records.filter((r) => r.exitPrice !== null);
  const totalPnl = closedTrades.reduce((sum, r) => sum + r.estimatedPnl, 0);
  const winners = closedTrades.filter((r) => r.estimatedPnl > 0).length;
  const winRate = closedTrades.length > 0 ? winners / closedTrades.length : 0;
  const sharpe = computePaperTradingSharpe(records);

  return {
    sharpe,
    totalPnl,
    tradeCount: closedTrades.length,
    winRate,
  };
}
